### ISSUE TITLE
`ProxyConfigSpec` also configures environment variables of the control plane components

### ISSUE THREAD

**Issue by bavarianbidi** [vmware/cluster-api-provider-cloud-director#299]
### Describe the bug

A set  `ProxyConfigSpec` in the `vcdcluster` object does not even configure the proxy for `containerd` ([as documented](https://github.com/vmware/cluster-api-provider-cloud-director/blob/f4a210aa4850c1a487fc3067a8da064db569615e/api/v1beta1/vcdcluster_types.go#L46)) it also configures the pod manifest files of the control plane components and inject the proxy variable there.

As the variables `HTTP_PROXY`/`HTTPS_PROXY` and `NO_PROXY` are exported to the shell where `kubeadm` is getting called (xref: [`cloud_init.tmpl`](https://github.com/vmware/cluster-api-provider-cloud-director/blob/f4a210aa4850c1a487fc3067a8da064db569615e/controllers/cluster_scripts/cloud_init.tmpl#L110-L115)), `kubeadm` is discovering the proxy variables and injecting these to the control plane manifests.

If `noProxy` isn't configured (as not needed when only fetching images from public registries through a proxy), the kubernetes control-plane components are failling as the make use of the `HTTPS_PROXY` and `HTTP_PROXY` variable for every request as `NO_PROXY` is empty.

### Reproduction steps

1. Creating a cluster where only `httpProxy` and `httpsProxy` is configured in `vcdcluster.spec.proxyConfig`
2. if a in-cluster webhook is applied, the API-server tries to reach this webhook via the proxy-server

### Expected behavior

According to the documentation that only `containerd` is configured for the proxy, the control-plane components should work with an unset `NO_PROXY` variable.

### Additional context

* [slack thread in #kubeadm community](https://kubernetes.slack.com/archives/C2P1JHS2E/p1665990172084419) regarding the behavior of autodiscovering proxy vars
* [kubeadm issue #2771](https://github.com/kubernetes/kubeadm/issues/2771) to track the current kubeadm implementation
* [kubeadm #2770](https://github.com/kubernetes/kubeadm/issues/2770) to track the issue with wrong json patches

**Comment by bavarianbidi** [comment]
One addition: during the initial definition of the proxy-variables i didn't know the apiserver loadbalancer IP. It means i have to create the cluster first with the proxy variables (and hope that the proxy-server itself is able to reach the kubernetes api server). and once the cluster got created i have to set the api-server IP to the `noProxy` list. This behavior could lead to a chicken-egg problem.

**Comment by arunmk** [comment]
@bavarianbidi do you mean that `kubeadm` should not use the environment variables and only `containerd` should use it?

**Comment by bavarianbidi** [comment]
> @bavarianbidi do you mean that `kubeadm` should not use the environment variables and only `containerd` should use it?

@arunmk that's what i expect reading the documentation (`kubectl explain vcdcluster.spec.proxyconfig`).

**Comment by bavarianbidi** [comment]
And it might be also a chicken-egg problem: if the k8s-api loadbalancer is generated with a dynamic ip i might not know during the cluster-creation, the `noProxy` value doesn't contain that ip. This might lead to the behavior, that `kube-scheduler`, `kube-controller` are connecting to the api-server to the loadbalancer IP via the configured proxy server. And if the proxyserver isn't able to route traffic to that IP, scheduler and controller manager aren't able to start.

**Comment by bavarianbidi** [comment]
Just FYI:
We currently removed the build-in proxy configuration ([link to internal PR](https://github.com/giantswarm/cluster-api-provider-cloud-director/pull/1)) and refering to a proxy-config for containerd from a secret in the CAPI management cluster:

```yaml
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
[...]
spec:
  kubeadmConfigSpec:
    files:
      - path: /etc/systemd/system/containerd.service.d/99-http-proxy.conf
        permissions: "0600"
        contentFrom:
          secret:
            name: mycluster-cluster-values-containerd-proxy
            key: containerdProxy    
    preKubeadmCommands:
    - systemctl daemon-reload
    - systemctl restart containerd
```
